package com.revature.app;

import java.util.Arrays;

public class StringDriver {
    public static void main(String[] args){
        String s1 = "Hello";
        System.out.println(s1 + ", world");
        System.out.println(s1);

        //Strings are immutable, it cannot be changed.
        s1.concat(", world!");
        System.out.println(s1); //s1 is unchanged

        //Assigning a new value to s1 seems to work
        s1 = s1.concat(", world!");
        System.out.println(s1);

        // Common String API methods
        char firstChar = s1.charAt(0);
        System.out.println(firstChar);

        String allButFirst = s1.substring(1);
        System.out.println(allButFirst);

        String anotherSubstring = s1.substring(1,4); // non-inclusive upper-bound
        System.out.println(anotherSubstring);

        int stringLength = s1.length();
        System.out.println(stringLength);

        String quickFox = "The quick brown fox jumped over the lazy dog";
        String[] words = quickFox.split(" ");
        System.out.println(Arrays.toString(words));

        String antotherSplitExample = "here-we-go";
        String[] moreWords = antotherSplitExample.split("-");
        System.out.println(Arrays.toString(moreWords));

        // -----------------------------------

        //String Pool

        // A special area of heap memory that stores unique String objects within

        String s2 = "hello";
        String s3 = "hello";
        System.out.println(s2 == s3); //Refernce equality (same object in memory?)
        System.out.println(s2.equals(s3)); // by default same as ==

        //So string literals with the same value point to the same object in memory

        // Can we change this?

        String s4 = new String("hello");
        System.out.println(s2.equals(s4));
        System.out.println(s2 == s4);
        s4 = s4.intern(); // tells Java that to create a String object within the String Pool with this string's value
        System.out.println(s2 == s4);

        String s5 = "";
        String s6 = s5.concat("hello"); // String objects generated by String API methods are not automatically put into the String pool
        System.out.println(s2 == s6); // false

        //-------------------------------------------------

        // StringBuilder/Buffer

//        StringBuilder strBuilder = ""; // cannot instantiate StringBuilders with String literals
        StringBuilder strBuilder = new StringBuilder("some initial string value");

        // Method chaining is possible here, b/c the append method returns a reference to this StringBuilder object
        strBuilder.append(", appended value")
                .append(", and another")
                .append(", last one");

        String builtString = strBuilder.toString();

        System.out.println(builtString);
        System.out.println(builtString.equals(strBuilder));
    }

    public static String returnsString(char[] chars) {
        return new String(chars); // probably one of the only actual use cases of new String();
    }
}
